name = "SPH"
uuid = "df2485c2-37c5-459c-ab44-70b522d49cc7"
authors = ["Thomas Marks <marksta@umich.edu> and contributors"]
version = "0.1.0"

[deps]
Piecewise = "da5dcb9c-6581-414c-b5f9-c7d9cf6920b7"

[compat]
julia = "1"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
